SUPABASE_URL = "https://njhjquehihrdauasqfvj.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qaGpxdWVoaWhyZGF1YXNxZnZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyOTg4NTIsImV4cCI6MjA2MDg3NDg1Mn0.foz-jJKIuuNarAs11A53dP_BWsYoXAA41DuIwvtlicY"
